export const myProjects = [
    {
      title: "Admin Dashboard",
      description: "Responsive Application built in react contains +10 pages which can admin control website ",
      category: ["all", "react"],
      image: "./Admin Dashboard.png",
      link: "https://hk-admindashboard.netlify.app/",
      github: "https://github.com/HusseinAbdelnasser/React-Admin-Dashboard",
    },
    {
      title: "eCommerce Website",
      description: "Responsive Single Page built in react using strapi database",
      category: ["react", "all"],
      image: "./E-commerce.png",
      link: "https://hk-ecommerce-strapi.netlify.app/",
      github: "https://github.com/HusseinAbdelnasser/ecommerce-strapi",
    },
    {
      title: "E-Learning",
      description: "Responsive Multi Pages App built with html, css, js and bootstrap for learning courses",
      category: ["bootstrap", "all"],
      image: "./elearning.png",
      link: "https://joyful-mochi-ed68fe.netlify.app/",
      github: "https://github.com/HusseinAbdelnasser/E-Learning.git",
    },
    {
      title: "Impact",
      description: "Responsive Application is built with html,css,js,bootstrap and other libraries",
      category: ["bootstrap", "all"],
      image: "./impact.png",
      link: "https://impacttemplate.netlify.app/",
      github: "https://github.com/HusseinAbdelnasser/Imp_Template.git",
    },
    {
      title: "Bondi",
      description: "Responsive template is built with html and css",
      category: ["css", "all"],
      image: "./bondi.png",
      link: "https://hkbonditemplate.netlify.app/",
      github: "https://github.com/HusseinAbdelnasser/Bondi-Template",
    },
    {
      title: "eCommerce",
      description: "Responsive eCommerce is built with html and css",
      category: ["css", "all"],
      image: "ecommerce.png",
      link: "https://hk-ecommercehtml.netlify.app/",
      github: "https://github.com/HusseinAbdelnasser/Html_Css_eCommerce",
    },
    {
      title: "Github Repos",
      description: "Application built with html,css and js.User can get github repos when you write github username",
      category: ["js", "all"],
      image: "repos.png",
      link: "https://radiant-souffle-5ae09e.netlify.app/",
      github: "https://github.com/HusseinAbdelnasser/Javascript-Tutorials.git",
    },
    {
      title: "ToDoList App",
      description: "App built with html,css and js.User can add tasks and  delete it",
      category: ["js", "all"],
      image: "/todolist.png",
      link: "https://coruscating-chebakia-c9d109.netlify.app/",
      github: "https://github.com/HusseinAbdelnasser/Javascript-Tutorials.git",
    },
  ]
  